create extension if not exists citext with schema extensions;

create table public.roles (
  role_key text primary key,
  label text not null,
  color text not null default '#2ECC40',
  sort_order integer not null default 0,
  is_super boolean not null default false,
  hidden_signup boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.role_permissions (
  role_key text not null references public.roles(role_key) on update cascade on delete cascade,
  page_key text not null,
  can_view boolean not null default false,
  can_add boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  primary key (role_key, page_key)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username extensions.citext not null unique,
  email extensions.citext not null unique,
  role_key text not null default 'Agent' references public.roles(role_key),
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  profile_image text,
  theme_mode text not null default 'light' check (theme_mode in ('light', 'dark')),
  custom_colors jsonb not null default '{}'::jsonb,
  monthly_target_vnd bigint not null default 0 check (monthly_target_vnd >= 0),
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id)
);

create table public.app_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id)
);

create table public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  level text not null check (level in ('City', 'Area', 'Society')),
  parent_id bigint references public.locations(id) on delete restrict,
  slug text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id),
  unique (parent_id, name)
);

create table public.amenities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id)
);

create table public.owners (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  email extensions.citext,
  identity_number text,
  address text,
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id)
);

create table public.properties (
  id bigint generated by default as identity primary key,
  reference_code text not null unique,
  title text not null,
  slug text not null unique,
  description text,
  property_type text not null check (property_type in ('House','Flat','Upper Portion','Lower Portion','Farm House','Plot','Commercial Plot','Shop','Office','Warehouse','Building')),
  listing_type text not null check (listing_type in ('Sale','Rent')),
  status text not null check (status in ('Draft','Available','Reserved','Sold','Rented','Withdrawn')),
  price_vnd bigint not null check (price_vnd >= 0),
  rent_frequency text check (rent_frequency is null or rent_frequency in ('Monthly','Yearly')),
  area_size numeric(14,2) check (area_size is null or area_size >= 0),
  area_unit text not null default 'm²',
  bedrooms smallint check (bedrooms is null or bedrooms >= 0),
  bathrooms smallint check (bathrooms is null or bathrooms >= 0),
  location_id bigint references public.locations(id) on delete restrict,
  address text,
  latitude numeric(10,7),
  longitude numeric(10,7),
  owner_id bigint references public.owners(id) on delete restrict,
  owner_name_snapshot text,
  owner_phone_snapshot text,
  assigned_agent_id uuid references public.profiles(id) on delete restrict,
  is_featured boolean not null default false,
  views_count bigint not null default 0 check (views_count >= 0),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id)
);

create table public.property_amenities (
  property_id bigint not null references public.properties(id) on delete cascade,
  amenity_id bigint not null references public.amenities(id) on delete restrict,
  primary key (property_id, amenity_id)
);

create table public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  storage_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id)
);

create table public.property_documents (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  file_name text not null,
  storage_path text not null,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id)
);

create table public.property_expenses (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  expense_date date not null,
  category text not null check (category in ('Maintenance','Marketing','Legal','Utility','Other')),
  amount_vnd bigint not null check (amount_vnd >= 0),
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id)
);

create table public.leads (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email extensions.citext,
  source text not null check (source in ('Website','WhatsApp','Facebook','Walk-in','Referral','Phone Call','Other')),
  interest_type text not null check (interest_type in ('Buy','Rent','Sell','Rent Out')),
  property_id bigint references public.properties(id) on delete set null,
  preferred_location_id bigint references public.locations(id) on delete set null,
  budget_min_vnd bigint check (budget_min_vnd is null or budget_min_vnd >= 0),
  budget_max_vnd bigint check (budget_max_vnd is null or budget_max_vnd >= 0),
  message text,
  status text not null check (status in ('New','Contacted','Qualified','Viewing Scheduled','Negotiating','Won','Lost')),
  lost_reason text,
  assigned_agent_id uuid references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id),
  check (budget_max_vnd is null or budget_min_vnd is null or budget_max_vnd >= budget_min_vnd)
);

create unique index leads_open_phone_unique
  on public.leads (phone)
  where deleted_at is null and status not in ('Won', 'Lost');

create table public.lead_offers (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  property_id bigint references public.properties(id) on delete set null,
  offered_by text not null check (offered_by in ('Buyer','Seller')),
  amount_vnd bigint not null check (amount_vnd > 0),
  status text not null check (status in ('Open','Countered','Accepted','Rejected')),
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

create table public.follow_ups (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete restrict,
  assigned_agent_id uuid references public.profiles(id) on delete restrict,
  type text not null check (type in ('Call','WhatsApp','Email','Meeting','Note')),
  notes text,
  due_at timestamptz,
  status text not null check (status in ('Pending','Completed','Cancelled')),
  completed_at timestamptz,
  reminder_sent_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id)
);

create table public.appointments (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete restrict,
  property_id bigint not null references public.properties(id) on delete restrict,
  agent_id uuid not null references public.profiles(id) on delete restrict,
  scheduled_at timestamptz not null,
  duration_minutes integer not null default 30 check (duration_minutes between 5 and 1440),
  status text not null check (status in ('Scheduled','Confirmed','Completed','Cancelled','No Show')),
  notes text,
  cancellation_reason text,
  reminder_sent_at timestamptz,
  interest_level text check (interest_level is null or interest_level in ('Hot','Warm','Cold')),
  feedback text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id)
);

create table public.deals (
  id bigint generated by default as identity primary key,
  deal_type text not null check (deal_type in ('Sale','Rent')),
  property_id bigint not null references public.properties(id) on delete restrict,
  lead_id bigint references public.leads(id) on delete set null,
  buyer_name text not null,
  buyer_phone text not null,
  agent_id uuid not null references public.profiles(id) on delete restrict,
  deal_amount_vnd bigint not null check (deal_amount_vnd > 0),
  commission_pct numeric(7,4) not null default 0 check (commission_pct >= 0),
  commission_amount_vnd bigint generated always as (round(deal_amount_vnd * commission_pct / 100.0)) stored,
  agent_share_pct numeric(7,4) not null default 0 check (agent_share_pct between 0 and 100),
  agent_share_amount_vnd bigint generated always as (round(round(deal_amount_vnd * commission_pct / 100.0) * agent_share_pct / 100.0)) stored,
  agent_paid_at timestamptz,
  token_amount_vnd bigint not null default 0 check (token_amount_vnd >= 0 and token_amount_vnd <= deal_amount_vnd),
  status text not null check (status in ('Token','Agreement','Completed','Cancelled')),
  closed_at timestamptz,
  cancellation_reason text,
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id)
);

create unique index deals_one_open_per_property
  on public.deals (property_id)
  where deleted_at is null and status not in ('Completed', 'Cancelled');

create table public.deal_payments (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on delete restrict,
  paid_at timestamptz not null default now(),
  amount_vnd bigint not null check (amount_vnd > 0),
  method text not null check (method in ('Cash','Bank Transfer','Cheque','Online')),
  reference text,
  notes text,
  received_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.tenancies (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete restrict,
  deal_id bigint references public.deals(id) on delete restrict,
  tenant_name text not null,
  tenant_phone text not null,
  monthly_rent_vnd bigint not null check (monthly_rent_vnd > 0),
  security_deposit_vnd bigint not null default 0 check (security_deposit_vnd >= 0),
  start_date date not null,
  end_date date,
  rent_due_day smallint not null default 5 check (rent_due_day between 1 and 28),
  status text not null check (status in ('Active','Ended')),
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  deleted_at timestamptz,
  deleted_by uuid references public.profiles(id),
  check (end_date is null or end_date >= start_date)
);

create unique index tenancies_one_active_per_property
  on public.tenancies (property_id)
  where deleted_at is null and status = 'Active';

create table public.rent_payments (
  id bigint generated by default as identity primary key,
  tenancy_id bigint not null references public.tenancies(id) on delete restrict,
  rent_month date not null check (extract(day from rent_month) = 1),
  amount_vnd bigint not null check (amount_vnd > 0),
  paid_at timestamptz not null default now(),
  method text not null check (method in ('Cash','Bank Transfer','Cheque','Online')),
  reference text,
  received_by uuid not null references public.profiles(id) on delete restrict,
  unique (tenancy_id, rent_month)
);

create table public.tenancy_renewals (
  id bigint generated by default as identity primary key,
  tenancy_id bigint not null references public.tenancies(id) on delete restrict,
  renewed_at timestamptz not null default now(),
  old_rent_vnd bigint not null check (old_rent_vnd > 0),
  new_rent_vnd bigint not null check (new_rent_vnd > 0),
  new_end_date date,
  notes text,
  created_by uuid not null references public.profiles(id)
);

create table public.maintenance_items (
  id bigint generated by default as identity primary key,
  tenancy_id bigint not null references public.tenancies(id) on delete restrict,
  issue_date date not null default current_date,
  issue text not null,
  status text not null default 'Open' check (status in ('Open','Fixed')),
  cost_vnd bigint not null default 0 check (cost_vnd >= 0),
  fixed_at timestamptz,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.deposit_refunds (
  tenancy_id bigint primary key references public.tenancies(id) on delete restrict,
  deposit_vnd bigint not null check (deposit_vnd >= 0),
  deductions_vnd bigint not null default 0 check (deductions_vnd >= 0 and deductions_vnd <= deposit_vnd),
  refund_vnd bigint generated always as (deposit_vnd - deductions_vnd) stored,
  notes text,
  refunded_at timestamptz not null default now(),
  refunded_by uuid not null references public.profiles(id)
);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_username text not null,
  action text not null,
  details text,
  changes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index properties_agent_idx on public.properties(assigned_agent_id) where deleted_at is null;
create index properties_location_idx on public.properties(location_id) where deleted_at is null;
create index leads_agent_status_idx on public.leads(assigned_agent_id, status) where deleted_at is null;
create index follow_ups_agent_due_idx on public.follow_ups(assigned_agent_id, due_at) where deleted_at is null;
create index appointments_agent_date_idx on public.appointments(agent_id, scheduled_at) where deleted_at is null;
create index deals_agent_status_idx on public.deals(agent_id, status) where deleted_at is null;
create index deal_payments_deal_idx on public.deal_payments(deal_id, paid_at);
create index rent_payments_tenancy_idx on public.rent_payments(tenancy_id, rent_month);
create index logs_created_idx on public.activity_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','locations','amenities','owners','properties','leads','lead_offers','follow_ups','appointments','deals','tenancies']
  loop
    execute format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end $$;

create or replace function public.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$ select auth.uid() $$;

create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is not null and public.current_role() <> 'Admin' then
    if new.id <> old.id
       or new.username <> old.username
       or new.email <> old.email
       or new.role_key <> old.role_key
       or new.status <> old.status
       or new.monthly_target_vnd <> old.monthly_target_vnd
       or new.created_at <> old.created_at
       or new.created_by is distinct from old.created_by then
      raise exception 'Only an administrator may change identity, role, status, or target';
    end if;
  end if;
  return new;
end;
$$;

create trigger profiles_protect_privileges
before update on public.profiles
for each row execute function public.protect_profile_privileges();

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$ select p.role_key from public.profiles p where p.id = auth.uid() and p.status = 'Active' $$;

create or replace function public.is_manager_or_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$ select coalesce(public.current_role() in ('Admin','Manager'), false) $$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_username text;
begin
  requested_username := coalesce(nullif(trim(new.raw_user_meta_data ->> 'username'), ''), split_part(new.email, '@', 1));
  insert into public.profiles(id, username, email, role_key, status)
  values (new.id, requested_username, new.email, 'Agent', 'Active')
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.has_permission(requested_page text, requested_action text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(r.is_super or case requested_action
    when 'v' then rp.can_view
    when 'a' then rp.can_add
    when 'e' then rp.can_edit
    when 'd' then rp.can_delete
    else false end, false)
  from public.profiles p
  join public.roles r on r.role_key = p.role_key
  left join public.role_permissions rp on rp.role_key = p.role_key and rp.page_key = requested_page
  where p.id = auth.uid() and p.status = 'Active'
$$;

create or replace view public.deal_financials
with (security_invoker = true)
as
select d.*,
       coalesce(sum(p.amount_vnd), 0)::bigint as paid_vnd,
       greatest(d.deal_amount_vnd - coalesce(sum(p.amount_vnd), 0), 0)::bigint as balance_vnd
from public.deals d
left join public.deal_payments p on p.deal_id = d.id
group by d.id;

create or replace function public.validate_deal_payment()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  deal_total bigint;
  deal_status text;
  already_paid bigint;
begin
  select d.deal_amount_vnd, d.status
  into deal_total, deal_status
  from public.deals d
  where d.id = new.deal_id and d.deleted_at is null
  for update;

  if not found then raise exception 'Deal not found'; end if;
  if deal_status = 'Cancelled' then raise exception 'Deal is cancelled'; end if;

  select coalesce(sum(p.amount_vnd), 0)::bigint
  into already_paid
  from public.deal_payments p
  where p.deal_id = new.deal_id and (tg_op = 'INSERT' or p.id <> new.id);

  if already_paid + new.amount_vnd > deal_total then
    raise exception 'Overpayment blocked. Remaining balance: %', deal_total - already_paid;
  end if;
  return new;
end;
$$;

create trigger deal_payments_validate
before insert or update on public.deal_payments
for each row execute function public.validate_deal_payment();

create or replace function public.record_deal_payment(
  target_deal_id bigint,
  payment_amount_vnd bigint,
  payment_method text default 'Cash',
  payment_reference text default '',
  payment_notes text default '',
  payment_time timestamptz default now()
)
returns public.deal_financials
language plpgsql
security invoker
set search_path = ''
as $$
declare
  locked_deal public.deals;
  already_paid bigint;
  result_row public.deal_financials;
begin
  if not public.has_permission('deals', 'e') then raise exception 'Access denied'; end if;
  if payment_amount_vnd <= 0 then raise exception 'Payment amount must be positive'; end if;
  if payment_method not in ('Cash','Bank Transfer','Cheque','Online') then raise exception 'Invalid payment method'; end if;

  select * into locked_deal from public.deals where id = target_deal_id and deleted_at is null for update;
  if not found then raise exception 'Deal not found'; end if;
  if locked_deal.status = 'Cancelled' then raise exception 'Deal is cancelled'; end if;
  if not public.is_manager_or_admin() and locked_deal.agent_id <> auth.uid() then raise exception 'Not your deal'; end if;

  select coalesce(sum(amount_vnd), 0)::bigint into already_paid from public.deal_payments where deal_id = target_deal_id;
  if already_paid + payment_amount_vnd > locked_deal.deal_amount_vnd then
    raise exception 'Overpayment blocked. Remaining balance: %', locked_deal.deal_amount_vnd - already_paid;
  end if;

  insert into public.deal_payments(deal_id, paid_at, amount_vnd, method, reference, notes, received_by)
  values (target_deal_id, payment_time, payment_amount_vnd, payment_method, payment_reference, payment_notes, auth.uid());

  select * into result_row from public.deal_financials where id = target_deal_id;
  return result_row;
end;
$$;

create or replace view public.tenancy_financials
with (security_invoker = true)
as
select t.*,
       coalesce(p.collected_vnd, 0)::bigint as collected_vnd,
       case when t.status = 'Active' then
         greatest(
           (((extract(year from current_date)::integer - extract(year from t.start_date)::integer) * 12
             + extract(month from current_date)::integer - extract(month from t.start_date)::integer
             + case when extract(day from current_date) >= t.rent_due_day then 1 else 0 end)
            * t.monthly_rent_vnd) - coalesce(p.collected_vnd, 0), 0
         )::bigint
       else 0::bigint end as arrears_vnd
from public.tenancies t
left join (
  select tenancy_id, sum(amount_vnd)::bigint as collected_vnd
  from public.rent_payments group by tenancy_id
) p on p.tenancy_id = t.id;

alter table public.roles enable row level security;
alter table public.role_permissions enable row level security;
alter table public.profiles enable row level security;
alter table public.app_settings enable row level security;
alter table public.locations enable row level security;
alter table public.amenities enable row level security;
alter table public.owners enable row level security;
alter table public.properties enable row level security;
alter table public.property_amenities enable row level security;
alter table public.property_images enable row level security;
alter table public.property_documents enable row level security;
alter table public.property_expenses enable row level security;
alter table public.leads enable row level security;
alter table public.lead_offers enable row level security;
alter table public.follow_ups enable row level security;
alter table public.appointments enable row level security;
alter table public.deals enable row level security;
alter table public.deal_payments enable row level security;
alter table public.tenancies enable row level security;
alter table public.rent_payments enable row level security;
alter table public.tenancy_renewals enable row level security;
alter table public.maintenance_items enable row level security;
alter table public.deposit_refunds enable row level security;
alter table public.activity_logs enable row level security;

create policy profiles_read on public.profiles for select to authenticated using (public.has_permission('users','v') or id = auth.uid());
create policy profiles_self_update on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy roles_read on public.roles for select to authenticated using (true);
create policy permissions_read on public.role_permissions for select to authenticated using (true);
create policy permissions_admin on public.role_permissions for all to authenticated using (public.current_role() = 'Admin') with check (public.current_role() = 'Admin');
create policy settings_read on public.app_settings for select to authenticated using (true);
create policy settings_admin on public.app_settings for all to authenticated using (public.current_role() = 'Admin') with check (public.current_role() = 'Admin');

create policy locations_read on public.locations for select to authenticated using (public.has_permission('locations','v'));
create policy locations_add on public.locations for insert to authenticated with check (public.has_permission('locations','a'));
create policy locations_edit on public.locations for update to authenticated using (public.has_permission('locations','e')) with check (public.has_permission('locations','e'));
create policy locations_delete on public.locations for delete to authenticated using (public.has_permission('locations','d'));
create policy amenities_read on public.amenities for select to authenticated using (public.has_permission('amenities','v'));
create policy amenities_admin_write on public.amenities for all to authenticated using (public.current_role() = 'Admin') with check (public.current_role() = 'Admin');

create policy owners_read on public.owners for select to authenticated using (public.has_permission('owners','v'));
create policy owners_add on public.owners for insert to authenticated with check (public.has_permission('owners','a'));
create policy owners_edit on public.owners for update to authenticated using (public.has_permission('owners','e')) with check (public.has_permission('owners','e'));
create policy owners_delete on public.owners for delete to authenticated using (public.has_permission('owners','d'));

create policy properties_read on public.properties for select to authenticated using (public.has_permission('properties','v'));
create policy properties_public_read on public.properties for select to anon using (deleted_at is null and published_at is not null and status = 'Available');
create policy properties_add on public.properties for insert to authenticated with check (public.has_permission('properties','a') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy properties_edit on public.properties for update to authenticated using (public.has_permission('properties','e') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid())) with check (public.has_permission('properties','e') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy properties_delete on public.properties for delete to authenticated using (public.has_permission('properties','d'));

create policy leads_read on public.leads for select to authenticated using (public.has_permission('leads','v') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy leads_add on public.leads for insert to authenticated with check (public.has_permission('leads','a') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy leads_edit on public.leads for update to authenticated using (public.has_permission('leads','e') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid())) with check (public.has_permission('leads','e') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy leads_delete on public.leads for delete to authenticated using (public.has_permission('leads','d'));

create policy followups_read on public.follow_ups for select to authenticated using (public.has_permission('followups','v') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy followups_write on public.follow_ups for all to authenticated using (public.has_permission('followups','e') and (public.is_manager_or_admin() or assigned_agent_id = auth.uid())) with check ((public.has_permission('followups','a') or public.has_permission('followups','e')) and (public.is_manager_or_admin() or assigned_agent_id = auth.uid()));
create policy appointments_read on public.appointments for select to authenticated using (public.has_permission('appointments','v') and (public.is_manager_or_admin() or agent_id = auth.uid()));
create policy appointments_write on public.appointments for all to authenticated using (public.has_permission('appointments','e') and (public.is_manager_or_admin() or agent_id = auth.uid())) with check ((public.has_permission('appointments','a') or public.has_permission('appointments','e')) and (public.is_manager_or_admin() or agent_id = auth.uid()));

create policy deals_read on public.deals for select to authenticated using (public.has_permission('deals','v') and (public.is_manager_or_admin() or agent_id = auth.uid()));
create policy deals_add on public.deals for insert to authenticated with check (public.has_permission('deals','a') and (public.is_manager_or_admin() or agent_id = auth.uid()));
create policy deals_edit on public.deals for update to authenticated using (public.has_permission('deals','e') and (public.is_manager_or_admin() or agent_id = auth.uid())) with check (public.has_permission('deals','e') and (public.is_manager_or_admin() or agent_id = auth.uid()));
create policy deals_delete on public.deals for delete to authenticated using (public.has_permission('deals','d'));
create policy deal_payments_read on public.deal_payments for select to authenticated using (exists(select 1 from public.deals d where d.id = deal_id and public.has_permission('deals','v') and (public.is_manager_or_admin() or d.agent_id = auth.uid())));
create policy deal_payments_add on public.deal_payments for insert to authenticated with check (received_by = auth.uid() and exists(select 1 from public.deals d where d.id = deal_id and public.has_permission('deals','e') and (public.is_manager_or_admin() or d.agent_id = auth.uid())));

create policy tenancies_read on public.tenancies for select to authenticated using (public.has_permission('tenancies','v') and exists(select 1 from public.properties p where p.id = property_id and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy tenancies_write on public.tenancies for all to authenticated using (public.has_permission('tenancies','e') and exists(select 1 from public.properties p where p.id = property_id and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid()))) with check ((public.has_permission('tenancies','a') or public.has_permission('tenancies','e')) and exists(select 1 from public.properties p where p.id = property_id and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy rent_payments_read on public.rent_payments for select to authenticated using (exists(select 1 from public.tenancies t join public.properties p on p.id = t.property_id where t.id = tenancy_id and public.has_permission('tenancies','v') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy rent_payments_add on public.rent_payments for insert to authenticated with check (received_by = auth.uid() and exists(select 1 from public.tenancies t join public.properties p on p.id = t.property_id where t.id = tenancy_id and public.has_permission('tenancies','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));

create policy logs_read on public.activity_logs for select to authenticated using (public.has_permission('logs','v'));
create policy logs_add on public.activity_logs for insert to authenticated with check (actor_id = auth.uid());

-- Child records inherit access from their owning property/lead/tenancy.
create policy property_amenities_read on public.property_amenities for select to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','v')));
create policy property_amenities_write on public.property_amenities for all to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid()))) with check (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy property_images_read on public.property_images for select to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','v')));
create policy property_images_write on public.property_images for all to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid()))) with check (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy property_documents_read on public.property_documents for select to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','v')));
create policy property_documents_write on public.property_documents for all to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid()))) with check (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy property_expenses_read on public.property_expenses for select to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','v')));
create policy property_expenses_write on public.property_expenses for all to authenticated using (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid()))) with check (exists(select 1 from public.properties p where p.id = property_id and public.has_permission('properties','e') and (public.is_manager_or_admin() or p.assigned_agent_id = auth.uid())));
create policy offers_read on public.lead_offers for select to authenticated using (exists(select 1 from public.leads l where l.id = lead_id and public.has_permission('leads','v') and (public.is_manager_or_admin() or l.assigned_agent_id = auth.uid())));
create policy offers_write on public.lead_offers for all to authenticated using (exists(select 1 from public.leads l where l.id = lead_id and public.has_permission('leads','e') and (public.is_manager_or_admin() or l.assigned_agent_id = auth.uid()))) with check (exists(select 1 from public.leads l where l.id = lead_id and public.has_permission('leads','e') and (public.is_manager_or_admin() or l.assigned_agent_id = auth.uid())));
create policy renewals_read on public.tenancy_renewals for select to authenticated using (exists(select 1 from public.tenancies t join public.properties p on p.id=t.property_id where t.id=tenancy_id and public.has_permission('tenancies','v') and (public.is_manager_or_admin() or p.assigned_agent_id=auth.uid())));
create policy renewals_write on public.tenancy_renewals for all to authenticated using (public.is_manager_or_admin()) with check (public.is_manager_or_admin());
create policy maintenance_read on public.maintenance_items for select to authenticated using (exists(select 1 from public.tenancies t join public.properties p on p.id=t.property_id where t.id=tenancy_id and public.has_permission('tenancies','v') and (public.is_manager_or_admin() or p.assigned_agent_id=auth.uid())));
create policy maintenance_write on public.maintenance_items for all to authenticated using (exists(select 1 from public.tenancies t join public.properties p on p.id=t.property_id where t.id=tenancy_id and public.has_permission('tenancies','e') and (public.is_manager_or_admin() or p.assigned_agent_id=auth.uid()))) with check (exists(select 1 from public.tenancies t join public.properties p on p.id=t.property_id where t.id=tenancy_id and public.has_permission('tenancies','e') and (public.is_manager_or_admin() or p.assigned_agent_id=auth.uid())));
create policy refunds_read on public.deposit_refunds for select to authenticated using (exists(select 1 from public.tenancies t join public.properties p on p.id=t.property_id where t.id=tenancy_id and public.has_permission('tenancies','v') and (public.is_manager_or_admin() or p.assigned_agent_id=auth.uid())));
create policy refunds_write on public.deposit_refunds for all to authenticated using (public.is_manager_or_admin()) with check (public.is_manager_or_admin());

insert into public.roles(role_key, label, color, sort_order, is_super, hidden_signup) values
  ('Admin', 'Quản trị viên', '#6a1b9a', 1, true, true),
  ('Manager', 'Quản lý', '#0074D9', 2, false, true),
  ('Agent', 'Nhân viên', '#2ECC40', 3, false, false);

insert into public.role_permissions(role_key, page_key, can_view, can_add, can_edit, can_delete)
select role_key, page_key,
  case when role_key='Admin' then true when page_key in ('dashboard','ai','properties','leads','followups','appointments','deals','tenancies','agreements','reports','owners','settings') then true when role_key='Manager' and page_key in ('users','locations','logs') then true else false end,
  case when role_key='Admin' then true when role_key='Manager' and page_key in ('properties','leads','followups','appointments','deals','tenancies','agreements','owners','locations') then true when role_key='Agent' and page_key in ('properties','leads','followups','appointments','deals','agreements','owners') then true else false end,
  case when role_key='Admin' then true when role_key='Manager' and page_key in ('properties','leads','followups','appointments','deals','tenancies','owners','locations') then true when role_key='Agent' and page_key in ('properties','leads','followups','appointments','deals','tenancies') then true else false end,
  case when role_key='Admin' then true when role_key='Manager' and page_key in ('properties','leads','followups','appointments','deals') then true else false end
from public.roles
cross join (values ('dashboard'),('ai'),('properties'),('leads'),('followups'),('appointments'),('deals'),('tenancies'),('agreements'),('reports'),('owners'),('locations'),('amenities'),('users'),('settings'),('logs'),('trash')) pages(page_key);

insert into public.app_settings(setting_key, setting_value) values
  ('crm', '{"currency":"VND","locale":"vi-VN","timezone":"Asia/Ho_Chi_Minh","commissionPctSale":1,"commissionPctRent":100,"agentSharePct":40,"renewalIncrementPct":10,"roundRobin":false}'::jsonb);
